[v1]
"ast-grep 0.22.3 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "ast-grep",
    "sg",
]
"cargo-bloat 0.12.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bloat"]
"cargo-diet 1.2.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-diet"]
"cargo-insta 1.39.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-insta"]
"cargo-outdated 0.15.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-outdated"]
"cargo-update 13.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"cargo-binstall 1.6.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-binstall"]
"cargo-deadlinks 0.8.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-deadlinks",
    "deadlinks",
]
"cargo-deny 0.14.23 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-deny"]
"cargo-expand 1.0.88 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-fuzz 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-fuzz"]
"cargo-llvm-cov 0.6.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-llvm-cov"]
"cargo-release 0.25.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-release"]
"cargo-watch 8.5.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-watch"]
"cargo-workspaces 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-workspaces",
    "cargo-ws",
]
"create-tauri-app 3.14.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-create-tauri-app"]
"eza 0.18.16 (registry+https://github.com/rust-lang/crates.io-index)" = ["eza"]
"flamegraph 0.6.5 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-flamegraph",
    "flamegraph",
]
"gitoxide 0.35.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "ein",
    "gix",
]
"mdbook 0.4.40 (registry+https://github.com/rust-lang/crates.io-index)" = ["mdbook"]
"procs 0.14.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["procs"]
"ripgrep 14.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
