[v1]
"cargo-bloat 0.12.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-bloat",
]
"cargo-deadlinks 0.8.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-deadlinks",
	"deadlinks",
]
"cargo-diet 1.2.7 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-diet",
]
"cargo-fuzz 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-fuzz",
]
"cargo-outdated 0.16.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-outdated",
]
"cargo-typify 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-typify",
]
"cargo-watch 8.5.3 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-watch",
]
"cargo-workspaces 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-workspaces",
	"cargo-ws",
]
"create-tauri-app 4.5.9 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-create-tauri-app",
]
"cross 0.2.5 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cross",
	"cross-util",
]
"flamegraph 0.6.7 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-flamegraph",
	"flamegraph",
]
"hd 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hd"]
"ripgrep 14.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"rg",
]
"bat 0.25.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"hyperfine 1.19.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"hyperfine",
]
"lla 0.3.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["lla"]
"ast-grep 0.35.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"ast-grep",
	"sg",
]
"cargo-llvm-cov 0.6.16 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-llvm-cov",
]
"cargo-msrv 0.18.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-msrv",
]
"cargo-release 0.25.17 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-release",
]
"cargo-update 16.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-install-update",
	"cargo-install-update-config",
]
"eza 0.20.23 (registry+https://github.com/rust-lang/crates.io-index)" = ["eza"]
"gitoxide 0.41.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"ein",
	"gix",
]
"just 1.39.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["just"]
"mdbook 0.4.45 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"mdbook",
]
"procs 0.14.9 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"procs",
]
"samply 0.13.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"samply",
]
"zizmor 1.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"zizmor",
]
"zoxide 0.9.7 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"zoxide",
]
"tree-sitter-cli 0.25.3 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"tree-sitter",
]
"cargo-audit 0.21.2 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-audit",
]
"cargo-expand 1.0.101 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-expand",
]
"cargo-insta 1.42.2 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-insta",
]
"cargo-binstall 1.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-binstall",
]
"wasm-tools 1.227.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"wasm-tools",
]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"tokei",
]
"cargo-instruments 0.4.12 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-instruments",
]
"cargo-nextest 0.9.92 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-nextest",
]
