[v1]
"cargo-bloat 0.12.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-bloat",
]
"cargo-deadlinks 0.8.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-deadlinks",
	"deadlinks",
]
"cargo-diet 1.2.7 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-diet",
]
"cargo-watch 8.5.3 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-watch",
]
"cross 0.2.5 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cross",
	"cross-util",
]
"hd 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hd"]
"ripgrep 14.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"rg",
]
"bat 0.25.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"hyperfine 1.19.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"hyperfine",
]
"samply 0.13.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"samply",
]
"cargo-audit 0.21.2 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-audit",
]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"tokei",
]
"cargo-instruments 0.4.12 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-instruments",
]
"cargo-msrv 0.18.4 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-msrv",
]
"cargo-outdated 0.17.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-outdated",
]
"cargo-release 0.25.18 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-release",
]
"procs 0.14.10 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"procs",
]
"cargo-insta 1.43.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-insta",
]
"cargo-fuzz 0.13.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-fuzz",
]
"cargo-workspaces 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-workspaces",
	"cargo-ws",
]
"taplo-cli 0.10.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"taplo",
]
"zoxide 0.9.8 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"zoxide",
]
"cargo-expand 1.0.114 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-expand",
]
"cargo-llvm-cov 0.6.18 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-llvm-cov",
]
"cargo-update 17.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-install-update",
	"cargo-install-update-config",
]
"create-tauri-app 4.6.2 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-create-tauri-app",
]
"eza 0.23.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["eza"]
"gitoxide 0.45.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"ein",
	"gix",
]
"just 1.42.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["just"]
"mdbook 0.4.52 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"mdbook",
]
"tree-sitter-cli 0.25.8 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"tree-sitter",
]
"ast-grep 0.39.4 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"ast-grep",
	"sg",
]
"cargo-binstall 1.15.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-binstall",
]
"cargo-nextest 0.9.103 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-nextest",
]
"cargo-typify 0.4.3 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-typify",
]
"flamegraph 0.6.9 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"cargo-flamegraph",
	"flamegraph",
]
"lla 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["lla"]
"wasm-tools 1.237.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"wasm-tools",
]
"zizmor 1.12.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
	"zizmor",
]
