[v1]
"ast-grep 0.37.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "ast-grep",
  "sg",
]
"bat 0.25.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"cargo-audit 0.21.2 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "cargo-audit",
]
"cargo-binstall 1.12.3 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "cargo-binstall",
]
"cargo-bloat 0.12.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "cargo-bloat",
]
"cargo-deadlinks 0.8.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "cargo-deadlinks",
  "deadlinks",
]
"cargo-diet 1.2.7 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "cargo-diet",
]
"cargo-expand 1.0.106 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "cargo-expand",
]
"cargo-fuzz 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "cargo-fuzz",
]
"cargo-insta 1.42.2 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "cargo-insta",
]
"cargo-instruments 0.4.12 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "cargo-instruments",
]
"cargo-llvm-cov 0.6.16 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "cargo-llvm-cov",
]
"cargo-msrv 0.18.4 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "cargo-msrv",
]
"cargo-nextest 0.9.94 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "cargo-nextest",
]
"cargo-outdated 0.17.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "cargo-outdated",
]
"cargo-release 0.25.18 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "cargo-release",
]
"cargo-typify 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "cargo-typify",
]
"cargo-update 16.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "cargo-install-update",
  "cargo-install-update-config",
]
"cargo-watch 8.5.3 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "cargo-watch",
]
"cargo-workspaces 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "cargo-workspaces",
  "cargo-ws",
]
"create-tauri-app 4.5.9 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "cargo-create-tauri-app",
]
"cross 0.2.5 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "cross",
  "cross-util",
]
"eza 0.21.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["eza"]
"flamegraph 0.6.7 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "cargo-flamegraph",
  "flamegraph",
]
"gitoxide 0.42.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "ein",
  "gix",
]
"hd 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hd"]
"hyperfine 1.19.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "hyperfine",
]
"just 1.40.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["just"]
"lla 0.3.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["lla"]
"mdbook 0.4.48 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "mdbook",
]
"procs 0.14.10 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "procs",
]
"ripgrep 14.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "rg",
]
"samply 0.13.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "samply",
]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "tokei",
]
"tree-sitter-cli 0.25.3 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "tree-sitter",
]
"wasm-tools 1.229.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "wasm-tools",
]
"zizmor 1.5.2 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "zizmor",
]
"zoxide 0.9.7 (registry+https://github.com/rust-lang/crates.io-index)" = [
  "zoxide",
]
